import type { Metadata } from "next";
import { geistSans, geistMono } from "@/fonts";
import "@/styles/global.scss";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { ReduxProvider } from "@/store/provider/ReduxProvider";
import GoogleLoader from "@/google/GoogleLoader/GoogleLoader";

export const metadata: Metadata = {
  title: "Foxtcon",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
      suppressHydrationWarning
    >
      <body suppressHydrationWarning>
        <ReduxProvider>
          <ToastContainer />
          <GoogleLoader> {children}</GoogleLoader>
        </ReduxProvider>
      </body>
    </html>
  );
}
