import type { Metadata } from "next";
import { geistSans, geistMono } from "@/fonts";
import "@/styles/global.scss";

export const metadata: Metadata = {
  title: "Foxtcon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
      suppressHydrationWarning
    >
      <body suppressHydrationWarning>{children}</body>
    </html>
  );
}
